swagger: "2.0"
info:
  title: rubberyconf API
  description: rubbery conf API definition.
  version: 0.0.1
host: rubberyconf
basePath: /
schemes:
  - http
paths:
  /feature/{featureId}/{branch}:
    get:
      summary: Returns featureId's value only. Mainly to be called by clients. 
      description: Every configuration has detailed structure with several fields nested. The method returns only value after all business rules have been applied.
      parameters:
        - in: path
          name: featureId
          required: true
          type: string
          description: feature id
        - in: path
          name: branch
          type: string
          description: Only if we're using git service as datasource
      produces:
        - application/json
        - application/text
      responses:
        200:
          description: OK
        204:
          description: configuration not found
        500:
          description: something went wrong
 
  /conf/{featureId}/{branch}:
    get:
      summary: Returns featureId full information (all fields)
      description: Every configuration has detailed structure with several fields nested. The method returns full information. No rules applied.
      parameters:
        - in: path
          name: featureId
          required: true
          type: string
          description: feature id
        - in: path
          name: branch
          type: string
          description: Only if we're using git service as datasource

      produces:
        - application/json
      responses:
        200:
          description: OK
        204:
          description: configuration not found
        500:
          description: something went wrong
    post:
      summary: Create a new configuration indexed with name featureId
      description: Store a new configuration in rubberyconf.
      parameters:
        - in: path
          name: featureId
          required: true
          type: string
        - in: body
          name: configuration
          description: configuration description
          required: true
          schema:
            $ref: '#/definitions/featureConfiguration'
      produces:
        - application/text
      responses:
        200: 
          description: OK
        500:
          description: something went wrong
    delete:
      summary: Delete configuration
      description: Delete configuratio with key featureId
      parameters:
        - in: path
          name: featureId
          required: true
          type: string
      produces:
        - application/text
      responses:
        200:
          description: OK
        500:
          description: something went wrong

definitions:
  featureConfiguration:
    type: object
    properties:
      name:
        type: string
      default:
        type: object
        properties:
          value: 
            type: object
            properties:
              data:
                type: string
              type:
                type: string
              
          