api: #rubberyconf server
  port: 8080
  cache: "None" #options: InMemory, Redis or None
  source: "InMemory" #options: InMemory, Gogs or Github
  logs: 
    - Console
    - Elastic
  default_ttl: "10s"

database: 
  collections:
    metrics: "metrics"
    sessionids: "usersessions"
  databasename: "rubberyconfdb"
  url: "mongodb://localhost:27017/?authSource=admin&readPreference=primary&directConnection=true&ssl=false"

redis:
  user: ""
  pass: ""
  url: "127.0.0.1:6379"


gitserver:
  user: "joanmi"
  pass: "xU@GtZQX4kqSVmv"
  url: "http://localhost:3000/acme/configuration"
  apitoken: "929f19719c9c9aac8c37c3a3766ebfce211cf5a9"

elastic:
  logs:
    index: "rbtraces"
  url: "http://localhost:9200"

