api:
  port: 8080
  type: "inMemory"
  sourcetype: "Gogs"

database:
  collections:
    metrics: "metrics"
  databasename: "rubberyconfdb"
  url: "http://localhost:27017"

cache:
  user: ""
  pass: ""
  url: "127.0.0.1:6379"


gitserver:
  user: "joanmi"
  pass: "xU@GtZQX4kqSVmv"
  url: "http://localhost:3000/acme/configuration"
  apitoken: "929f19719c9c9aac8c37c3a3766ebfce211cf5a9"

elastic:
  index: "rbtraces"
  url: "http://localhost:9200"

