# copy this file with your own configuration
api: #rubberyconf server
  port: 8080
  cache: "None" #options: InMemory, Redis or None
  source: "InMemory" #options: Mongodb, InMemory, Gogs or Github
  logs: 
    - Console
    - Elastic
  default_ttl: "10s" # ttl stored a configuration in cache 
  options:
    loglevel: "debug" #options: debug,info,error,warning 

database: 
  collections:
    metrics: "metrics"
    sessionids: "usersessions"
    features: "features"
  databasename: "rubberyconfdb"
  url: "mongodb://localhost:27017/?authSource=admin&readPreference=primary&directConnection=true&ssl=false"
  timeout: "2s"

redis:
  user: ""
  pass: ""
  url: "127.0.0.1:6379"
  timeout: "2s"


gitserver:
  user: ""
  email: ""
  pass: ""
  url: "http://localhost:3000/acme/configuration"
  apitoken: "" #personal access token insted of user/pass
  repo: ""
  branchdefault: "master"
  timeout: "2s"

elastic:
  logs:
    index: "rbtraces"
  url: "http://localhost:9200"
  timeout: "2s"

